// Generated by CoffeeScript 1.6.3
(function() {
  var CBAuthentication;

  CBAuthentication = angular.module("CBAuthentication", []);

  CBAuthentication.controller("LoginCtrl", function($scope) {
    var appConfig, auth, currentVirtualBrowser, googleStrategy, localStrategy;
    $scope.email = null;
    $scope.password = null;
    $scope.emailError = null;
    $scope.loginError = null;
    $scope.resetSuccessMsg = null;
    $scope.isDisabled = false;
    $scope.showEmailButton = false;
    currentVirtualBrowser = cloudbrowser.currentVirtualBrowser;
    appConfig = currentVirtualBrowser.getAppConfig();
    auth = cloudbrowser.auth;
    googleStrategy = auth.getGoogleStrategy();
    localStrategy = auth.getLocalStrategy();
    $scope.$watch("email + password", function() {
      $scope.loginError = null;
      $scope.isDisabled = false;
      return $scope.resetSuccessMsg = null;
    });
    $scope.$watch("email", function() {
      return $scope.emailError = null;
    });
    $scope.googleLogin = function() {
      return googleStrategy.login();
    };
    $scope.login = function() {
      if (!$scope.email || !$scope.password) {
        return $scope.loginError = "Please provide both the Email ID and the password to login";
      } else {
        $scope.isDisabled = true;
        return localStrategy.login({
          user: new cloudbrowser.app.User($scope.email, 'local'),
          password: $scope.password,
          callback: function(success) {
            if (!success) {
              $scope.$apply(function() {
                return $scope.loginError = "Invalid Credentials";
              });
            }
            return $scope.isDisabled = false;
          }
        });
      }
    };
    return $scope.sendResetLink = function() {
      if (($scope.email == null) || !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/.test($scope.email.toUpperCase())) {
        return $scope.emailError = "Please provide a valid email ID";
      } else {
        $scope.resetDisabled = true;
        return auth.sendResetLink(new cloudbrowser.app.User($scope.email, 'local'), function(success) {
          if (success) {
            $scope.resetSuccessMsg = "A password reset link has been sent to your email ID.";
          } else {
            $scope.$apply(function() {
              return $scope.emailError = "This email ID is not registered with us.";
            });
          }
          return $scope.$apply(function() {
            return $scope.resetDisabled = false;
          });
        });
      }
    };
  });

  CBAuthentication.controller("SignupCtrl", function($scope) {
    var appConfig, currentVirtualBrowser, googleStrategy, localStrategy;
    $scope.email = null;
    $scope.password = null;
    $scope.vpassword = null;
    $scope.emailError = null;
    $scope.signupError = null;
    $scope.passwordError = null;
    $scope.successMessage = false;
    $scope.isDisabled = false;
    currentVirtualBrowser = cloudbrowser.currentVirtualBrowser;
    appConfig = currentVirtualBrowser.getAppConfig();
    googleStrategy = cloudbrowser.auth.getGoogleStrategy();
    localStrategy = cloudbrowser.auth.getLocalStrategy();
    $scope.$watch("email", function(nval, oval) {
      $scope.emailError = null;
      $scope.signupError = null;
      $scope.isDisabled = false;
      $scope.successMessage = false;
      return appConfig.isUserRegistered(new cloudbrowser.app.User($scope.email, 'local'), function(exists) {
        if (exists) {
          return $scope.$apply(function() {
            $scope.emailError = "Account with this Email ID already exists!";
            return $scope.isDisabled = true;
          });
        }
      });
    });
    $scope.$watch("password+vpassword", function() {
      $scope.signupError = null;
      $scope.passwordError = null;
      return $scope.isDisabled = false;
    });
    $scope.googleLogin = function() {
      return googleStrategy.signup();
    };
    return $scope.signup = function() {
      $scope.isDisabled = true;
      if (($scope.email == null) || ($scope.password == null)) {
        return $scope.signupError = "Must provide both Email and Password!";
      } else if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/.test($scope.email.toUpperCase())) {
        return $scope.emailError = "Not a valid Email ID!";
      } else {
        return localStrategy.signup({
          user: new cloudbrowser.app.User($scope.email, 'local'),
          password: $scope.password,
          callback: function() {
            return $scope.$apply(function() {
              return $scope.successMessage = true;
            });
          }
        });
      }
    };
  });

}).call(this);
