// Generated by CoffeeScript 1.6.3
(function() {
  var CBHomePage;

  CBHomePage = angular.module("CBHomePage", []);

  CBHomePage.controller("MainCtrl", function($scope) {
    var App, currentVirtualBrowser, server;
    server = cloudbrowser.serverConfig;
    currentVirtualBrowser = cloudbrowser.currentVirtualBrowser;
    $scope.apps = [];
    App = (function() {
      function App() {}

      App.add = function(api) {
        var app;
        app = {};
        app.api = api;
        return $scope.$apply(function() {
          return $scope.apps.push(app);
        });
      };

      App.remove = function(mountPoint) {
        return $scope.$apply(function() {
          return $scope.apps = $.grep($scope.apps, function(element, index) {
            return element.api.getMountPoint() !== mountPoint;
          });
        });
      };

      return App;

    })();
    server.listApps({
      filters: {
        "public": true
      },
      callback: function(apps) {
        var app, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = apps.length; _i < _len; _i++) {
          app = apps[_i];
          _results.push(App.add(app));
        }
        return _results;
      }
    });
    server.addEventListener('madePublic', function(app) {
      return App.add(app);
    });
    server.addEventListener('madePrivate', function(mountPoint) {
      return App.remove(mountPoint);
    });
    return $scope.leftClick = function(url) {
      return currentVirtualBrowser.redirect(url);
    };
  });

  CBHomePage.filter("removeSlash", function() {
    return function(input) {
      return input.substring(1);
    };
  });

}).call(this);
