// Generated by CoffeeScript 1.6.3
(function() {
  var CBAdmin;

  CBAdmin = angular.module("CBAdmin", []);

  CBAdmin.controller("AppCtrl", function($scope) {
    var App, curVB, fileUploader, serverConfig, toggle;
    $scope.safeApply = function(fn) {
      var phase;
      phase = this.$root.$$phase;
      if (phase === '$apply' || phase === '$digest') {
        if (fn) {
          return fn();
        }
      } else {
        return this.$apply(fn);
      }
    };
    $scope.setError = function(err) {
      $scope.error = err;
      return setTimeout(function() {
        return $scope.safeApply(function() {
          return $scope.error = null;
        });
      }, 5000);
    };
    $scope.apps = [];
    App = (function() {
      function App() {}

      App.camelCaseToWords = function(camelCaseString) {
        return camelCaseString.replace(/([A-Z])/g, ' $1').replace(/^./, function(str) {
          return str.toUpperCase();
        });
      };

      App.add = function(appConfig) {
        var app, _i, _len, _ref;
        _ref = $scope.apps;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          app = _ref[_i];
          if (app.mountPoint === appConfig.getMountPoint()) {
            return;
          }
        }
        app = {
          url: appConfig.getUrl(),
          api: appConfig,
          name: appConfig.getName(),
          description: appConfig.getDescription(),
          mountPoint: appConfig.getMountPoint(),
          isPublic: appConfig.isAppPublic(),
          mounted: appConfig.isMounted(),
          browserLimit: appConfig.getBrowserLimit(),
          isAuthEnabled: appConfig.isAuthConfigured(),
          instantiationStrategy: App.camelCaseToWords(appConfig.getInstantiationStrategy())
        };
        appConfig.getUsers(function(err, users) {
          if (err) {
            return console.log(err);
          } else {
            return $scope.safeApply(function() {
              return app.numUsers = users.length;
            });
          }
        });
        appConfig.getBrowsers(function(err, browsers) {
          if (err) {
            return console.log(err);
          } else {
            return $scope.safeApply(function() {
              return app.numBrowsers = browsers.length;
            });
          }
        });
        App.setupEventListeners(app);
        return $scope.apps.push(app);
      };

      App.remove = function(mountPoint) {
        var app, idx, _i, _len, _ref;
        _ref = $scope.apps;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          app = _ref[_i];
          if (!(app.mountPoint === mountPoint)) {
            continue;
          }
          idx = $scope.apps.indexOf(app);
          return $scope.apps.splice(idx, 1);
        }
      };

      App.setupEventListeners = function(app) {
        app.api.addEventListener("addBrowser", function(vb) {
          return $scope.safeApply(function() {
            return app.numBrowsers++;
          });
        });
        app.api.addEventListener("removeBrowser", function(vbID) {
          return $scope.safeApply(function() {
            return app.numBrowsers--;
          });
        });
        app.api.addEventListener("addUser", function(user) {
          return $scope.safeApply(function() {
            return app.numUsers++;
          });
        });
        return app.api.addEventListener("removeUser", function(user) {
          return $scope.safeApply(function() {
            return app.numUsers--;
          });
        });
      };

      return App;

    })();
    curVB = cloudbrowser.currentBrowser;
    serverConfig = cloudbrowser.serverConfig;
    serverConfig.addEventListener("addApp", function(appConfig) {
      if (appConfig.isOwner()) {
        return App.add(appConfig);
      }
    });
    serverConfig.addEventListener("removeApp", function(appConfig) {
      return App.remove(appConfig);
    });
    fileUploader = curVB.createComponent('fileUploader', document.getElementById('file-uploader'), {
      legend: "Upload an Application",
      formClass: "form-inline well",
      buttonClass: "btn btn-primary"
    });
    fileUploader.addEventListener("cloudbrowser.upload", function(event) {
      var file, user, _ref;
      _ref = event.info, user = _ref.user, file = _ref.file;
      if (user !== $scope.user) {
        return;
      }
      if (file.type !== "application/x-gzip") {
        $scope.safeApply(function() {
          return $scope.setError("File must be a gzipped tarball");
        });
        return;
      }
      return serverConfig.uploadAndCreateApp(file.path, function(err, appConfig) {
        return $scope.safeApply(function() {
          if (err) {
            return $scope.setError(err);
          } else {
            return App.add(appConfig);
          }
        });
      });
    });
    $scope.user = curVB.getCreator();
    $scope.selectedApp = null;
    serverConfig.listApps({
      filters: ['perUser'],
      callback: function(err, appConfigs) {
        if (err) {
          return console.log(err);
        } else {
          return $scope.safeApply(function() {
            var appConfig, _i, _len;
            for (_i = 0, _len = appConfigs.length; _i < _len; _i++) {
              appConfig = appConfigs[_i];
              App.add(appConfig);
            }
            if ($scope.apps.length) {
              return $scope.safeApply(function() {
                return $scope.selectedApp = $scope.apps[0];
              });
            }
          });
        }
      }
    });
    $scope.leftClick = function(url) {
      return curVB.redirect(url);
    };
    $scope.editDescription = function(app) {
      if (app.api.isOwner()) {
        return app.editing = true;
      }
    };
    $scope.getBoxClass = function(app) {
      if (!app) {
        return;
      }
      if (app.mounted === true) {
        return "mounted";
      } else {
        return "disabled";
      }
    };
    toggle = function(app, property, method1, method2) {
      var err;
      if (app[property]) {
        err = app.api[method1]();
        if (err) {
          return console.log("" + method1 + " - " + err);
        } else {
          return app[property] = false;
        }
      } else {
        err = app.api[method2]();
        if (err) {
          return console.log("" + method2 + " - " + err);
        } else {
          return app[property] = true;
        }
      }
    };
    $scope.toggleMountDisable = function(app) {
      return toggle(app, 'mounted', 'disable', 'mount');
    };
    $scope.togglePrivacy = function(app) {
      return toggle(app, 'isPublic', 'makePrivate', 'makePublic');
    };
    $scope.toggleAuthentication = function(app) {
      return toggle(app, 'isAuthEnabled', 'disableAuthentication', 'enableAuthentication');
    };
    $scope.selectApp = function(app) {
      return $scope.selectedApp = app;
    };
    $scope.getAppClass = function(app) {
      if ($scope.selectedApp === app) {
        return "selected";
      } else {
        return "";
      }
    };
    $scope.logout = function() {
      return cloudbrowser.auth.logout();
    };
    return $scope.sortBy = function(predicate) {
      var reverseProp;
      $scope.predicate = predicate;
      reverseProp = "" + predicate + "-reverse";
      $scope[reverseProp] = !$scope[reverseProp];
      return $scope.reverse = $scope[reverseProp];
    };
  });

  CBAdmin.filter("removeSlash", function() {
    return function(input) {
      if (!input) {
        return;
      }
      if (input === "/") {
        return "Home Page";
      } else {
        return input.substring(1);
      }
    };
  });

  CBAdmin.directive('ngHasfocus', function() {
    return function(scope, element, attrs) {
      scope.$watch(attrs.ngHasfocus, function(nVal, oVal) {
        if (nVal) {
          return element[0].focus();
        }
      });
      element.bind('blur', function() {
        return scope.$apply(attrs.ngHasfocus + " = false", scope.selectedApp.api.setDescription(scope.selectedApp.description));
      });
      return element.bind('keydown', function(e) {
        if (e.which === 13) {
          return scope.$apply(attrs.ngHasfocus + " = false", scope.selectedApp.api.setDescription(scope.selectedApp.description));
        }
      });
    };
  });

}).call(this);
