// Generated by CoffeeScript 1.6.3
(function() {
  var AppInstance;

  AppInstance = (function() {
    function AppInstance(appInstanceConfig, format) {
      this.format = format;
      this.api = appInstanceConfig;
      this.id = appInstanceConfig.getID();
      this.name = appInstanceConfig.getName();
      this.owner = appInstanceConfig.getOwner();
      this.dateCreated = this.format.date(appInstanceConfig.getDateCreated());
      this.browserMgr = new CRUDManager(this.format, Browser);
      this.updateUsers();
    }

    AppInstance.prototype.updateUsers = function() {
      return this.readerwriters = this.api.getReaderWriters();
    };

    AppInstance.prototype.roles = [
      {
        name: 'can edit',
        perm: 'readwrite',
        checkMethods: ['isReaderWriter', 'isOwner'],
        grantMethod: 'addReaderWriter'
      }
    ];

    AppInstance.prototype.defaultRoleIndex = 0;

    return AppInstance;

  })();

  this.AppInstance = AppInstance;

}).call(this);
