// Generated by CoffeeScript 1.7.1
(function() {
  var CRUDManager;

  CRUDManager = (function() {
    function CRUDManager(format, TypeOfItems) {
      this.format = format;
      this.TypeOfItems = TypeOfItems;
      this.items = [];
    }

    CRUDManager.prototype.find = function(id) {
      var item, _i, _len, _ref;
      _ref = this.items;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        if (item.id === id) {
          return item;
        }
      }
    };

    CRUDManager.prototype.add = function(itemConfig) {
      var item;
      item = this.find(itemConfig.getID());
      if (!item) {
        item = new this.TypeOfItems(itemConfig, this.format);
        this.items.push(item);
      }
      return item;
    };

    CRUDManager.prototype.remove = function(item) {
      var idx;
      if (typeof item === "string") {
        item = this.find(item);
      }
      idx = this.items.indexOf(item);
      if (idx !== -1) {
        return this.items.splice(idx, 1);
      } else {
        return null;
      }
    };

    return CRUDManager;

  })();

  this.CRUDManager = CRUDManager;

}).call(this);
