// Generated by CoffeeScript 1.7.1
(function() {
  var CBAdminInterface;

  CBAdminInterface = angular.module('CBAdminInterface', ['CBAdminInterface.models', 'CBAdminInterface.services', 'CBAdminInterface.directives', 'CBAdminInterface.controller']);

}).call(this);
