// Generated by CoffeeScript 1.6.3
(function() {
  var Async, CBAdminInterface, NwGlobal;

  Async = require('async');

  NwGlobal = require('nwglobal');

  CBAdminInterface = angular.module("CBAdminInterface.controller", ['CBAdminInterface.models']);

  CBAdminInterface.controller("AppCtrl", [
    '$scope', 'cb-appManager', function($scope, appManager) {
      var addApp, addAppInstance, addBrowser, addToUserList, addUser, curVB, fileUploader, listsToRoles, name, path, removeAppInstance, removeBrowser, removeFromUserList, serverConfig, setupEventListeners, toggleMethods, _ref;
      $scope.templates = {
        "switch": "switch.html",
        appTable: "app_table.html",
        appUsers: "app_users.html",
        appBrowsers: "app_browsers.html",
        appInstances: "app_instances.html",
        appDescription: "app_description.html",
        searchAndLogout: "search_and_logout.html",
        selectedAppTable: "selected_app_table.html"
      };
      _ref = $scope.templates;
      for (name in _ref) {
        path = _ref[name];
        $scope.templates[name] = "" + __dirname + "/partials/" + path;
      }
      $scope.safeApply = function(fn) {
        var phase;
        phase = this.$root.$$phase;
        if (phase === '$apply' || phase === '$digest') {
          if (fn) {
            return fn();
          }
        } else {
          return this.$apply(fn);
        }
      };
      curVB = cloudbrowser.currentBrowser;
      serverConfig = cloudbrowser.serverConfig;
      $scope.search = "";
      $scope.apps = appManager.items;
      $scope.switches = ['isPublic', 'isAuthEnabled', 'mounted'];
      $scope.selectedApp = null;
      $scope.user = curVB.getCreator();
      $scope.setError = function(err) {
        $scope.error = err;
        return setTimeout(function() {
          return $scope.safeApply(function() {
            return $scope.error = null;
          });
        }, 5000);
      };
      listsToRoles = {
        owner: 'owner',
        owners: 'owner',
        readers: 'reader',
        readerwriters: 'readerwriter'
      };
      addToUserList = function(app, user, list, id, role) {
        var u;
        u = app.userMgr.add(user);
        return u[list].add({
          id: id,
          role: role
        });
      };
      removeFromUserList = function(app, user, list, id) {
        var u;
        u = app.userMgr.find(user);
        return u[list].remove(id);
      };
      addUser = function(app, user) {
        app.userMgr.add(user);
        return app.api.getBrowsers(user, function(err, browserConfigs) {
          var browserConfig, _i, _len, _results;
          _results = [];
          for (_i = 0, _len = browserConfigs.length; _i < _len; _i++) {
            browserConfig = browserConfigs[_i];
            if (browserConfig.isOwner(user)) {
              _results.push($scope.safeApply(function() {
                return u.owners.add({
                  id: browserConfig.getID(),
                  role: 'owner'
                });
              }));
            } else if (browserConfig.isReaderWriter(user)) {
              _results.push($scope.safeApply(function() {
                return u.readerwriters.add({
                  id: browserConfig.getID(),
                  role: 'readerwriter'
                });
              }));
            } else if (browserConfig.isReader(user)) {
              _results.push($scope.safeApply(function() {
                return u.readers.add({
                  id: browserConfig.getID(),
                  role: 'reader'
                });
              }));
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        });
      };
      addBrowser = function(app, browserConfig) {
        var appInstance, browser, list, listName, role, user, _i, _len;
        browser = app.browserMgr.find(browserConfig.getID());
        if (browser) {
          return browser;
        }
        browser = app.browserMgr.add(browserConfig);
        if (browser.appInstanceID) {
          appInstance = app.appInstanceMgr.add(browser.api.getAppInstanceConfig());
          appInstance.browserIDMgr.add(browser.id);
        }
        for (listName in listsToRoles) {
          role = listsToRoles[listName];
          list = browser[listName];
          if (list instanceof NwGlobal.Array) {
            for (_i = 0, _len = list.length; _i < _len; _i++) {
              user = list[_i];
              addToUserList(app, user, 'browserIDMgr', browser.id, role);
            }
          }
        }
        browser.api.addEventListener('connect', function(userInfo) {
          return $scope.safeApply(function() {
            return browser.connectedClientMgr.add(userInfo);
          });
        });
        browser.api.addEventListener('disconnect', function(email) {
          return $scope.safeApply(function() {
            return browser.connectedClientMgr.remove(email);
          });
        });
        return browser.api.addEventListener('share', function(userInfo) {
          user = userInfo.user, role = userInfo.role;
          return $scope.safeApply(function() {
            browser.updateUsers();
            return addToUserList(app, user, 'browserIDMgr', browser.id, role);
          });
        });
      };
      removeBrowser = function(app, browserID) {
        var appInstance, browser, list, listName, role, user, _results;
        browser = app.browserMgr.remove(browserID);
        if (browser.appInstanceID) {
          appInstance = app.appInstanceMgr.find(browser.appInstanceID);
          appInstance.browserIDMgr.remove(browser.id);
        }
        _results = [];
        for (listName in listsToRoles) {
          role = listsToRoles[listName];
          list = browser[listName];
          if (list instanceof NwGlobal.Array) {
            _results.push((function() {
              var _i, _len, _results1;
              _results1 = [];
              for (_i = 0, _len = list.length; _i < _len; _i++) {
                user = list[_i];
                _results1.push(removeFromUserList(app, user, 'browserIDMgr', browser.id));
              }
              return _results1;
            })());
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };
      addAppInstance = function(app, appInstanceConfig) {
        var appInstance, list, listName, role, user, _i, _len;
        appInstance = app.appInstanceMgr.find(appInstanceConfig.getID());
        if (appInstance) {
          return appInstance;
        }
        appInstance = app.appInstanceMgr.add(appInstanceConfig);
        for (listName in listsToRoles) {
          role = listsToRoles[listName];
          list = appInstance[listName];
          if (typeof list === "string") {
            addToUserList(app, list, 'appInstanceIDMgr', appInstance.id, role);
          } else if (list instanceof NwGlobal.Array) {
            for (_i = 0, _len = list.length; _i < _len; _i++) {
              user = list[_i];
              addToUserList(app, user, 'appInstanceIDMgr', appInstance.id, role);
            }
          }
        }
        return appInstance.api.addEventListener('share', function(user) {
          return $scope.safeApply(function() {
            appInstance.updateUsers();
            return addToUserList(app, user, 'appInstanceIDMgr', appInstance.id, 'readwriter');
          });
        });
      };
      removeAppInstance = function(app, appInstanceID) {
        var appInstance, list, listName, role, user, _results;
        appInstance = app.appInstanceMgr.remove(appInstanceID);
        _results = [];
        for (listName in listsToRoles) {
          role = listsToRoles[listName];
          list = appInstance[listName];
          if (typeof list === "string") {
            _results.push(removeFromUserList(app, list, 'appInstanceIDMgr', appInstance.id));
          } else if (list instanceof NwGlobal.Array) {
            _results.push((function() {
              var _i, _len, _results1;
              _results1 = [];
              for (_i = 0, _len = list.length; _i < _len; _i++) {
                user = list[_i];
                _results1.push(removeFromUserList(app, user, 'appInstanceIDMgr', appInstance.id));
              }
              return _results1;
            })());
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };
      setupEventListeners = function(app) {
        app.api.addEventListener("addBrowser", function(browserConfig) {
          return $scope.safeApply(function() {
            return addBrowser(app, browserConfig);
          });
        });
        app.api.addEventListener("removeBrowser", function(id) {
          return $scope.safeApply(function() {
            return removeBrowser(app, id);
          });
        });
        app.api.addEventListener("addAppInstance", function(appInstanceConfig) {
          return $scope.safeApply(function() {
            return addAppInstance(app, appInstanceConfig);
          });
        });
        app.api.addEventListener("removeAppInstance", function(id) {
          return $scope.safeApply(function() {
            return removeAppInstance(app, id);
          });
        });
        app.api.addEventListener("addUser", function(user) {
          return $scope.safeApply(function() {
            return addUser(app, user);
          });
        });
        return app.api.addEventListener("removeUser", function(user) {
          return $scope.safeApply(function() {
            return app.userMgr.remove(user);
          });
        });
      };
      addApp = function(appConfig) {
        var app;
        app = appManager.find(appConfig.getMountPoint());
        if (app) {
          return app;
        }
        app = appManager.add(appConfig);
        return Async.waterfall(NwGlobal.Array(function(next) {
          var browserConfig, _i, _len, _ref1;
          _ref1 = app.api.getAllBrowsers();
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            browserConfig = _ref1[_i];
            $scope.safeApply(function() {
              return addBrowser(app, browserConfig);
            });
          }
          return app.api.getAppInstances(next);
        }, function(appInstanceConfigs, next) {
          $scope.safeApply(function() {
            var appInstConfig, _i, _len, _results;
            _results = [];
            for (_i = 0, _len = appInstanceConfigs.length; _i < _len; _i++) {
              appInstConfig = appInstanceConfigs[_i];
              _results.push(addAppInstance(app, appInstConfig));
            }
            return _results;
          });
          return app.api.getUsers(next);
        }), function(err, users) {
          var user, _i, _len, _results;
          if (err) {
            return console.log(err);
          }
          setupEventListeners(app);
          _results = [];
          for (_i = 0, _len = users.length; _i < _len; _i++) {
            user = users[_i];
            _results.push($scope.safeApply(function() {
              return app.userMgr.add(user);
            }));
          }
          return _results;
        });
      };
      serverConfig.addEventListener("addApp", function(appConfig) {
        if (appConfig.isOwner()) {
          return addApp(appConfig);
        }
      });
      serverConfig.addEventListener("removeApp", function(mountPoint) {
        return appManager.remove(mountPoint);
      });
      fileUploader = curVB.createComponent('fileUploader', document.getElementById('file-uploader'), {
        legend: "Upload an Application",
        formClass: "form-inline well",
        buttonClass: "btn btn-primary"
      });
      fileUploader.addEventListener("cloudbrowser.upload", function(event) {
        var file, user, _ref1;
        _ref1 = event.info, user = _ref1.user, file = _ref1.file;
        if (user !== $scope.user) {
          return;
        }
        if (file.type !== "application/x-gzip") {
          $scope.safeApply(function() {
            return $scope.setError("File must be a gzipped tarball");
          });
          return;
        }
        return serverConfig.uploadAndCreateApp(file.path, function(err, appConfig) {
          return $scope.safeApply(function() {
            if (err) {
              return $scope.setError(err);
            } else {
              return App.add(appConfig);
            }
          });
        });
      });
      serverConfig.listApps(['perUser'], function(err, appConfigs) {
        var appConfig, _i, _len;
        if (err) {
          return console.log(err);
        } else {
          for (_i = 0, _len = appConfigs.length; _i < _len; _i++) {
            appConfig = appConfigs[_i];
            addApp(appConfig);
          }
          return $scope.safeApply(function() {
            var _ref1;
            return $scope.selectedApp = (_ref1 = $scope.apps) != null ? _ref1[0] : void 0;
          });
        }
      });
      $scope.leftClick = function(url) {
        return curVB.redirect(url);
      };
      $scope.editDescription = function() {
        var app;
        app = $scope.selectedApp;
        if (app.api.isOwner()) {
          return app.editing = true;
        }
      };
      $scope.getAppClass = function(app) {
        if ($scope.selectedApp === app) {
          return 'selected';
        } else {
          return '';
        }
      };
      $scope.select = function(app) {
        return $scope.selectedApp = app;
      };
      toggleMethods = {
        mounted: {
          on: 'mount',
          off: 'disable'
        },
        isPublic: {
          on: 'makePublic',
          off: 'makePrivate'
        },
        isAuthEnabled: {
          on: 'enableAuthentication',
          off: 'disableAuthentication'
        }
      };
      $scope.toggle = function(property) {
        var err, offMethod, onMethod;
        onMethod = toggleMethods[property].on;
        offMethod = toggleMethods[property].off;
        if ($scope.selectedApp[property]) {
          err = $scope.selectedApp.api[offMethod]();
          if (err) {
            return console.log("" + offMethod + " - " + err);
          } else {
            return $scope.selectedApp[property] = false;
          }
        } else {
          err = $scope.selectedApp.api[onMethod]();
          if (err) {
            return console.log("" + onMethod + " - " + err);
          } else {
            return $scope.selectedApp[property] = true;
          }
        }
      };
      $scope.sortBy = function(predicate) {
        var reverseProp;
        $scope.predicate = predicate;
        reverseProp = "" + predicate + "-reverse";
        $scope[reverseProp] = !$scope[reverseProp];
        return $scope.reverse = $scope[reverseProp];
      };
      return $scope.logout = function() {
        return cloudbrowser.auth.logout();
      };
    }
  ]);

}).call(this);
