// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('CBAdminInterface.directives', []);

  app.directive('cbHasfocus', function() {
    return function(scope, element, attrs) {
      scope.$watch(attrs.cbHasfocus, function(nVal, oVal) {
        if (nVal) {
          return element[0].focus();
        }
      });
      element.bind('blur', function() {
        return scope.$apply(attrs.cbHasfocus + " = false", app = scope.selectedApp, app.api.setDescription(app.description));
      });
      return element.bind('keydown', function(e) {
        if (e.which === 13) {
          return scope.$apply(attrs.cbHasfocus + " = false", app = scope.selectedApp, app.api.setDescription(app.description));
        }
      });
    };
  });

}).call(this);
