// Generated by CoffeeScript 1.8.0
(function() {
  var model;

  model = angular.module('CBAdminInterface.models', ['CBAdminInterface.services']);

  model.factory('cb-appManager', [
    'cb-format', function(format) {
      return new AppManager(App, format);
    }
  ]);

}).call(this);
