// Generated by CoffeeScript 1.8.0
(function() {
  var App, camelCaseToWords;

  camelCaseToWords = function(camelCaseString) {
    return camelCaseString.replace(/([A-Z])/g, ' $1').replace(/^./, function(str) {
      return str.toUpperCase();
    });
  };

  App = (function() {
    function App(appConfig, format) {
      this.url = appConfig.getUrl();
      this.api = appConfig;
      this.name = appConfig.getName();
      this.description = appConfig.getDescription();
      this.mountPoint = appConfig.getMountPoint();
      this.isPublic = appConfig.isAppPublic();
      this.mounted = appConfig.isMounted();
      this.browserLimit = appConfig.getBrowserLimit();
      this.isAuthEnabled = appConfig.isAuthConfigured();
      this.instantiationStrategy = camelCaseToWords(appConfig.getInstantiationStrategy());
      this.userMgr = new POJOListManager(User, 'emailID');
      this.browserMgr = new APIListManager(Browser, format);
      this.appInstanceMgr = new APIListManager(AppInstance, format);
      this.userMgr.visible = true;
      this.browserMgr.visible = true;
      this.appInstanceMgr.visible = true;
    }

    return App;

  })();

  this.App = App;

}).call(this);
