// Generated by CoffeeScript 1.8.0
(function() {
  var AppManager,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AppManager = (function(_super) {
    __extends(AppManager, _super);

    function AppManager(TypeOfItems, format, idProperty, idMethod) {
      this.TypeOfItems = TypeOfItems != null ? TypeOfItems : App;
      this.format = format;
      this.idProperty = idProperty != null ? idProperty : 'mountPoint';
      this.idMethod = idMethod != null ? idMethod : 'getMountPoint';
      this.items = [];
    }

    return AppManager;

  })(APIListManager);

  this.AppManager = AppManager;

}).call(this);
