// Generated by CoffeeScript 1.8.0
(function() {
  var AppInstance;

  AppInstance = (function() {
    function AppInstance(appInstanceConfig, format) {
      this.format = format;
      this.id = appInstanceConfig.getID();
      this.workerId = appInstanceConfig.getWorkerID();
      this.api = appInstanceConfig;
      this.url = appInstanceConfig.getURL();
      this.name = appInstanceConfig.getName();
      this.owner = appInstanceConfig.getOwner();
      this.browserIDMgr = new PrimitiveListManager();
      this.dateCreated = this.format(appInstanceConfig.getDateCreated());
      this.updateUsers();
    }

    AppInstance.prototype.updateUsers = function() {
      return this.readerwriters = this.api.getReaderWriters();
    };

    AppInstance.prototype.addUser = function(user) {
      return this.readerwriters.push(user);
    };

    return AppInstance;

  })();

  this.AppInstance = AppInstance;

}).call(this);
