// Generated by CoffeeScript 1.6.3
(function() {
  var Browser;

  Browser = (function() {
    function Browser(browserConfig, format) {
      var client, clients, _i, _len, _ref;
      this.id = browserConfig.getID();
      this.api = browserConfig;
      this.name = browserConfig.getName();
      this.dateCreated = format.date(browserConfig.getDateCreated());
      this.appInstanceID = (_ref = browserConfig.getAppInstanceConfig()) != null ? _ref.getID() : void 0;
      this.connectedClientMgr = new POJOListManager(null, 'address');
      if ((clients = browserConfig.getConnectedClients())) {
        for (_i = 0, _len = clients.length; _i < _len; _i++) {
          client = clients[_i];
          this.connectedClientMgr.add(client);
        }
      }
      if (browserConfig.getAppConfig().isAuthConfigured()) {
        this.creator = browserConfig.getCreator();
        this.updateUsers();
      }
    }

    Browser.prototype.updateUsers = function() {
      this.owners = this.api.getOwners();
      this.readers = this.api.getReaders();
      return this.readerwriters = this.api.getReaderWriters();
    };

    return Browser;

  })();

  this.Browser = Browser;

}).call(this);
