// Generated by CoffeeScript 1.8.0
(function() {
  var Browser;

  Browser = (function() {
    function Browser(browserConfig, format) {
      var client, clients, _i, _len;
      this.id = browserConfig.getID();
      this.workerId = browserConfig.getWorkerID();
      this.api = browserConfig;
      this.name = browserConfig.getName();
      this.dateCreated = format(browserConfig.getDateCreated());
      this.appInstanceID = browserConfig.getAppInstanceId();
      this.connectedClientMgr = new POJOListManager(null, 'address');
      if ((clients = browserConfig.getConnectedClients())) {
        for (_i = 0, _len = clients.length; _i < _len; _i++) {
          client = clients[_i];
          this.connectedClientMgr.add(client);
        }
      }
      if (browserConfig.getAppConfig().isAuthConfigured()) {
        this.creator = browserConfig.getCreator();
        this.updateUsers();
      }
    }

    Browser.prototype.updateUsers = function() {
      this.owners = this.api.getOwners();
      this.readers = this.api.getReaders();
      return this.readerwriters = this.api.getReaderWriters();
    };

    Browser.prototype.addUser = function(user, role) {
      switch (role) {
        case 'own':
          return this.owners.push(user);
        case 'readonly':
          return this.readers.push(user);
        case 'readwrite':
          return this.readerwriters.push(user);
      }
    };

    return Browser;

  })();

  this.Browser = Browser;

}).call(this);
