// Generated by CoffeeScript 1.8.0
(function() {
  var PrimitiveListManager;

  PrimitiveListManager = (function() {
    function PrimitiveListManager() {
      this.items = [];
    }

    PrimitiveListManager.prototype.find = function(item) {
      if (this.items.indexOf(item) !== -1) {
        return item;
      }
    };

    PrimitiveListManager.prototype.add = function(item) {
      var listItem;
      listItem = this.find(item);
      if (!listItem) {
        this.items.push(item);
      }
      return item;
    };

    PrimitiveListManager.prototype.remove = function(item) {
      var idx;
      idx = this.items.indexOf(item);
      if (idx !== -1) {
        return this.items.splice(idx, 1);
      }
    };

    return PrimitiveListManager;

  })();

  this.PrimitiveListManager = PrimitiveListManager;

}).call(this);
