// Generated by CoffeeScript 1.7.1
(function() {
  var User;

  User = (function() {
    function User(user) {
      this.emailID = user;
      this.browserIDMgr = new POJOListManager();
      this.appInstanceIDMgr = new POJOListManager();
    }

    return User;

  })();

  this.User = User;

}).call(this);
