// Generated by CoffeeScript 1.8.0
(function() {
  var CBLandingPage;

  CBLandingPage = angular.module('CBLandingPage', ['CBLandingPage.models', 'CBLandingPage.filters', 'CBLandingPage.services', 'CBLandingPage.directives', 'CBLandingPage.controllers.app', 'CBLandingPage.controllers.appInstance', 'CBLandingPage.controllers.browser']).config(function($sceDelegateProvider) {
    return $sceDelegateProvider.resourceUrlWhitelist(['self', "file://"]);
  });

}).call(this);
