// Generated by CoffeeScript 1.8.0
(function() {
  var managers;

  managers = angular.module('CBLandingPage.models', ['CBLandingPage.services']);

  managers.factory('cb-appInstanceManager', [
    'cb-format', function(format) {
      return new AppInstanceManager(format);
    }
  ]);

}).call(this);
