// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module("Chat3", []);

  app.controller("ChatCtrl", function($scope) {
    var browserId, chatManager, currentBrowser, newMessageHandler;
    $scope.safeApply = function(fn) {
      var phase;
      phase = this.$root.$$phase;
      if (phase === '$apply' || phase === '$digest') {
        if (fn) {
          return fn();
        }
      } else {
        return this.$apply(fn);
      }
    };
    $scope.roomName = null;
    $scope.selectedRoom = null;
    $scope.showCreateForm = false;
    $scope.showJoinForm = false;
    $scope.currentMessage = "";
    newMessageHandler = function(obj) {
      if (obj.browserId === browserId) {
        return;
      }
      return $scope.safeApply(function() {});
    };
    currentBrowser = cloudbrowser.currentBrowser;
    browserId = currentBrowser.getID();
    chatManager = cloudbrowser.currentAppInstanceConfig.getObj();
    $scope.user = chatManager.addUser(currentBrowser.getCreator(), newMessageHandler);
    $scope.toggleForm = function(type) {
      var formName;
      formName = "show" + type + "Form";
      return $scope[formName] = !$scope[formName];
    };
    $scope.openForm = function(type) {
      var formName;
      formName = "show" + type + "Form";
      return $scope[formName] = true;
    };
    $scope.closeForm = function(type) {
      var formName;
      formName = "show" + type + "Form";
      return $scope[formName] = false;
    };
    $scope.createRoom = function() {
      var err, room, _ref;
      _ref = chatManager.createRoom($scope.roomName), err = _ref[0], room = _ref[1];
      if (err) {
        $scope.error = err.message;
      } else {
        chatManager.addUserToRoom($scope.user, room);
        chatManager.emit("newRoom", {
          room: room,
          user: $scope.user,
          browserId: browserId
        });
      }
      $scope.roomName = null;
      return $scope.closeForm('Create');
    };
    $scope.joinRoom = function() {
      chatManager.addUserToRoom($scope.user, $scope.selectedRoom);
      $scope.selectedRoom = null;
      return $scope.closeForm('Join');
    };
    $scope.leaveRoom = function(room) {
      return chatManager.removeUserFromRoom($scope.user, room);
    };
    $scope.postMessage = function() {
      var msg;
      if ($scope.user.currentRoom) {
        msg = $scope.currentMessage;
        $scope.user.currentRoom.postMessage($scope.user, msg);
        $scope.currentMessage = "";
        return $scope.user.currentRoom.emit('newMessage', {
          user: $scope.user,
          msg: msg,
          browserId: browserId
        });
      }
    };
    return chatManager.on("newRoom", function(obj) {
      if (obj.browserId === browserId) {
        return;
      }
      return $scope.safeApply(function() {
        if (obj.user !== $scope.user) {
          return $scope.user.addToOtherRooms(obj.room);
        }
      });
    });
  });

  app.directive('enterSubmit', function() {
    var directive;
    return directive = {
      restrict: 'A',
      link: function(scope, element, attrs) {
        return element.bind('keydown', function(e) {
          if (e.which === 13) {
            scope.safeApply(function() {
              return scope.$eval(attrs.enterSubmit);
            });
            element.val('');
            element.text('');
            return e.preventDefault();
          }
        });
      }
    };
  });

}).call(this);
